# netlify.toml
[[headers]]
  for = "/*.html"
  [headers.values]
  Cache-Control = "no-store, max-age=0"

[[headers]]
  for = "/styles/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/scripts/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/data/*"
  [headers.values]
  Cache-Control = "public, max-age=60"
